### ISSUE TITLE
Tiny Shopware plugins to optimize the perfomance

### ISSUE THREAD

**Issue by sbenmoh** [FriendsOfShopware/friendsofshopware.github.io#12]
### 1. What is the benefit from your shopware extension to the community?

- HTTP/2 Server Push: Shopware generated CSS & JS automatically used in Server Push. (The server and client must support HTTP/2)
- HTML Minifier: minify generated HTML

### 2. Link to to current Github repository

- HTTP/2 Server Push: https://github.com/sbenmoh/SbHttp2Push
- HTML Minifier: https://github.com/sbenmoh/SbHtmlMinifier

### 3. Checklist

- [x] [I have read all rules and accepting it](https://github.com/FriendsOfShopware/friendsofshopware.github.io#rules)
- [ ] I have written tests and verified that they fail without my change

**Comment by shyim** [comment]
What would you say if we implement https://github.com/shopware/shopware/pull/1397/files as plugin?
It would be more extendable.

**Comment by sbenmoh** [comment]
Sure, it seems to be a good thing.
I just saw that you already have a plugin to improve Shopware pagespeed (https://github.com/shyim/ShyimPagespeed). What would you think to bundle all those features in this plugin? And add more new performance features in the future.

**Comment by shyim** [comment]
Yea i like the idea

**Comment by shyim** [comment]
I have created the repository https://github.com/FriendsOfShopware/FroshPerformance with the merge of your Plugins and the pagespeed plugin. I have also invited you to the repository :blush: and a note on the Friends Of Shopware repository. Thanks for your contribution! :blue_heart: :tada:
