### ISSUE TITLE
FroshTinker

### ISSUE THREAD

**Issue by jkrzefski** [FriendsOfShopware/friendsofshopware.github.io#15]
### 1. What is the benefit from your shopware extension to the community?

I recently made a [pull request](https://github.com/shopware/shopware/pull/2088) for Shopware to implement a new command `sw:tinker` to implement `psy/psysh`. Sadly this pull request was rejected for not following the planned roadmap of the product. In an attempt to not let my work on this go to waste, I propose to you my improved implementation as `frosh:tinker`. I have moved the code into a dedicated plugin and rebranded everything to frosh using the [default plugin repository](https://github.com/FriendsOfShopware/default-plugin-repo). The improvement I made is a caster for ORM objects as well as an easy way to provide and register other casters through a tagged service implementing an interface. For any further information, you can take a look at the readme file of the plugin.

### 2. Link to current Github repository

[jkrzefski/FroshTinker](https://github.com/jkrzefski/FroshTinker)

### 3. Checklist

- [x] [I have read all rules and accepting it](https://github.com/FriendsOfShopware/friendsofshopware.github.io#rules)
- [ ] I have written tests and verified that they fail without my change

**Comment by JoshuaBehrens** [comment]
I want to have it nau

**Comment by shyim** [comment]
Repo is created. I have added you also as Admin. We can put the plugin with Shopware 5.6 in the store, cause you require PHP 7.1
