### ISSUE TITLE
Plugins submission

### ISSUE THREAD

**Issue by dneustadt** [FriendsOfShopware/friendsofshopware.github.io#3]
### 1. What is the benefit from your shopware extension to the community?

DnVariantSwitch: Change/switch the variant of a product from checkout/cart and checkout/confirm and also via the off-canvas basket. No need to delete the article first, navigate back and add article in a different configuration. Demo: http://shopware.davidneustadt.de/checkout/cart

DnViewSnapshots: Persists serialized view variables, the path to template, request parameters etc to the database. Allows you to recover "recorded" views as if they were live, so you can recreate specific situations, e.g. a variety of different articles in the basket. As the markup isn't cached and the live template is fed with the persisted view variables, you can proceed to make changes on the stylesheet and template and preview under specialized conditions.

DnStateManagerDebug: Logs various information about events of the StateManager and PubSub. Allows filtering of specific event types, names and such.
**update**: proposed to be merged into [FroshProfiler](https://github.com/FriendsOfShopware/FroshProfiler)

DnBash: Adds a semi-interactive web shell to the Shopware backend. This is ment to be a temporary maintenance tool in cases where, for whatever reason, there is no access to the actual bash.
**update**: proposed to be included merged with [KskRemoteMaintenance](https://github.com/KSK-Agentur/KskRemoteMaintenance)

### 2. Link to to current Github repository

https://github.com/dneustadt/DnVariantSwitch
https://github.com/dneustadt/DnViewSnapshots
https://github.com/dneustadt/DnStateManagerDebug
https://github.com/dneustadt/DnBash

### 3. Checklist

- [x ] [I have read all rules and accepting it](https://github.com/FriendsOfShopware/friendsofshopware.github.io#rules)
- [ ] I have written tests and verified that they fail without my change

**Comment by shyim** [comment]
I would merge DnStateManagerDebug into the Profiler plugin, there is also logging of Javascript events. What do you think about that?

**Comment by dneustadt** [comment]
You're very welcome and encouraged to do so 👍

**Comment by shyim** [comment]
@jkrzefski @dneustadt Whats about merging DnBash and KskRemoteMaintenance (https://github.com/KSK-Agentur/KskRemoteMaintenance) into one plugin? Both plugins are for maintaince :)

**Comment by jkrzefski** [comment]
Sounds like a good idea to me. I think that could make a powerful allrounder. I was thinking about naming the frosh-version of my plugin `FroshWebdav` to make it more specific. But if we merge these two together, I think that a generic name like `FroshMaintenance` would fit it better. @dneustadt What do you think?

**Comment by dneustadt** [comment]
@jkrzefski i like the idea too and the proposed name sounds good 👍

**Comment by 8mylez** [comment]
@jkrzefski @dneustadt i think we should also integrate https://github.com/shyim/adminer-for-shopware to have a nice allrounder. (instead of porting it to FroshAdminer)

**Comment by dneustadt** [comment]
I'm all for it if @shyim agrees

**Comment by shyim** [comment]
@jkrzefski any updates there?
