### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by dneustadt** [FriendsOfShopware/friendsofshopware.github.io#4]
First draft proposition of a more stylized logo, applicable in more scenarios, ranging from lower resolutions to corporate design purposes.

![sketch](https://user-images.githubusercontent.com/9033214/38158214-7aabbc6e-3490-11e8-8a5b-df0858e66c53.png)

**Comment by Crease29** [comment]
I really like the idea and would be fine if we could use it as our logo.

**Comment by gurjarshakti** [comment]
thats looking cool @dneustadt :+1:
