### ISSUE TITLE
Database Reset

### ISSUE THREAD

**Issue by xndrdev** [FriendsOfShopware/friendsofshopware.github.io#6]
### 1. What is the benefit from your shopware extension to the community?

Easy resetting of the database, separated into modules like articles, customers and orders. With a nice ExtJS Backend. Also with a cronjob extension plus command line integration.

### 2. Link to to current Github repository

Not started the project, but will soon.

### 3. Checklist

- [x] [I have read all rules and accepting it](https://github.com/FriendsOfShopware/friendsofshopware.github.io#rules)
- [ ] I have written tests and verified that they fail without my change

**Comment by shyim** [comment]
What would the use-case for that? Shopware Git version has something similar already.

**Comment by xndrdev** [comment]
I use this on staging environments. So the main usage would be on shops that are online and not working with git.

**Comment by shyim** [comment]
@dneustadt @jkrzefski Could be that something what can be done in the Maintaince Plugin?

**Comment by dneustadt** [comment]
I've been there, truncating tables and deleting rows by hand e.g. when an export had gone wrong. I like the concept of a reset switch. So I would say, sure, let's get it in. 

Once this is green-lit, feel free to set up a branch for the feature. Each feature of the plugin should have a separate branch. Once production-ready we can merge all of them into master.

**Comment by xndrdev** [comment]
Alright. I will send a PR soon.
