### ISSUE TITLE
Many plugins

### ISSUE THREAD

**Issue by shyim** [FriendsOfShopware/friendsofshopware.github.io#7]
### 1. What is the benefit from your shopware extension to the community?
I have many shopware extensions in my account. I guess some plugins could be moved the Frosh.

**ShyimWebP**:
Adds WebP Support, decorates the Thumbnail Generator which generates addional webp image, and uses in serval places in frontend.

**ShyimCleaner**
Clears some tables where dead records are. Could be extended to clear cache folder from plugin manager. Or "Remove SwagSecurityHotFix2016xxx" with "SwagSecurity"

**ShyimBackendNotification**
Its a really bad name for that what it does. It synchronizes extjs windows with Google Firebase and shows 
 a warning when multiple backend users editing same entitiy

**ShyimMailCatcher**
Catches all mails and shows them in a extjs window

### 2. Link to to current Github repository
https://github.com/shyim/ShyimWebP
https://github.com/shyim/ShyimCleaner
https://github.com/shyim/ShyimBackendNotification
https://github.com/shyim/ShyimMailCatcher

### 3. Checklist

- [X] [I have read all rules and accepting it](https://github.com/FriendsOfShopware/friendsofshopware.github.io#rules)
- [ ] I have written tests and verified that they fail without my change

**Comment by xndrdev** [comment]
I think the ShyimWebP plugin is a good standalone plugin.
Maybe the ShyimCleaner and ShyimMailCatcher could be part of the maintenance plugin?

The ShyimBackendNotification should be extended with some more entities to be checked.

**Comment by shyim** [comment]
Is mail catching maintaince? I am not sure

**Comment by dneustadt** [comment]
IMHO maintenance means a relatively short window of time and anything installed for that matter should be removed afterwards. I don't think that description matches any of these plugins.

**Comment by xndrdev** [comment]
i think you're right. FroshMaintenance is just for the time of maintaining the shop. Therefore the ShyimCleaner could also be a standalone plugin. 

The Readme says that it's currently in work. Maybe it should be transffered once it's finished.
