### ISSUE TITLE
Domain: friendsofshopware.de

### ISSUE THREAD

**Issue by xndrdev** [FriendsOfShopware/friendsofshopware.github.io#9]
I would suggest the domain friendsofshopware.de and build a small website to be more visible, maybe add news and a list of the plugins.

I'll take the costs for the first year of the domain. The website can be hosted for free on github pages with hugo.

What do you think?

**Comment by shyim** [comment]
I would suggest to use for the Website https://www.netlify.com/ instead Github Pages. But the idea is cool :+1:

**Comment by JoshuaBehrens** [comment]
I am more a fan of jigsaw, but I am fine with everything that result in a static site.
